# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprocess',
            name='drop_status',
            field=models.CharField(choices=[('SCF', 'Successfull'), ('ERR', 'Unsuccessfull')], default=None, max_length=3, null=True),
        ),
    ]
