# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('viewflow', '0006_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('order_item', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('signed', models.BooleanField(default=False)),
                ('validated', models.BooleanField(default=False)),
                ('payment_date', models.DateField(null=True)),
                ('order_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Department')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
