# Generated by Django 3.1 on 2020-12-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
    ]
