# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0004_extend_fields_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMailProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('emergency', models.BooleanField(default=False)),
                ('recipient', models.CharField(blank=True, choices=[('SPV', 'Supervisor'), ('ADM', 'Administrator'), ('INA', 'Incident analyst')], max_length=3, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
