# Generated by Django 3.2.10 on 2022-01-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelloRestProcess',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('viewflow.process',),
        ),
    ]
