# Generated by Django 3.1rc1 on 2020-07-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0010_viewflow20'),
        ('helloworld', '0002_i18n'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelloWorldProcess',
        ),
        migrations.CreateModel(
            name='HelloWorldProcess',
            fields=[
            ],
            options={
                'verbose_name': 'World Request',
                'verbose_name_plural': 'World Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('viewflow.process',),
        ),
    ]
