# Generated by Django 3.2.10 on 2021-12-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "permissions": (
                    ("can_accept_bill", "Can accept department bill"),
                    ("can_sign_bill", "Can sign department bill"),
                    ("can_validate_bill", "Can validate department bill"),
                    (
                        "can_set_bill_paydate",
                        "Can set payment date for department bill",
                    ),
                    ("can_pay_bill", "Can pay department bill"),
                ),
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_item", models.CharField(max_length=250)),
                ("quantity", models.IntegerField()),
                ("description", models.TextField()),
                ("payment_date", models.DateField(null=True)),
                (
                    "order_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guardian_perms.department",
                    ),
                ),
            ],
        ),
    ]
