# Generated by Django 4.1.9 on 2023-08-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_widget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="name",
            field=models.CharField(default="test", max_length=150),
            preserve_default=False,
        ),
    ]
