# Generated by Django 4.1.9 on 2023-08-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_widget", "0002_attachment_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=150)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
