# Generated by Django 3.1rc1 on 2020-07-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='gay_friendly',
            field=models.BooleanField(null=True, verbose_name='gay friendly'),
        ),
    ]
