# Generated by Django 3.1 on 2020-11-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_auto_20200727_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='area',
            field=models.BigIntegerField(help_text='km²', verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='sea',
            name='area',
            field=models.BigIntegerField(help_text='km²', verbose_name='area'),
        ),
    ]
