# Generated by Django 4.1.9 on 2023-09-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GptResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("request", models.TextField()),
                ("response", models.TextField()),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-3.5-turbo", "GPT 3.5"),
                            ("gpt-3.5-turbo-16k", "GPT 3.5 (16k)"),
                            ("gpt-4", "GPT 4"),
                            ("Claude", "Claude"),
                        ],
                        max_length=150,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("url", models.URLField()),
                ("subtitles", models.FileField(upload_to="subtitles/")),
                ("video_timestamps", models.TextField(blank=True, default="")),
                ("data", models.JSONField(default={})),
                ("result", models.TextField(blank=True, default="")),
            ],
        ),
    ]
