# Generated by Django 3.2.10 on 2021-12-09 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("viewflow", "0010_viewflow20"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerVerificationProcess",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("viewflow.process",),
        ),
        migrations.CreateModel(
            name="OrderItemProcess",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("viewflow.process",),
        ),
        migrations.CreateModel(
            name="OrderProcess",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("viewflow.process",),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("quantity", models.IntegerField(default=1)),
                ("reserved", models.BooleanField(null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subprocess.orderprocess",
                    ),
                ),
            ],
        ),
    ]
